import Head from "next/head";
import { Inter } from "next/font/google";
import { Container, Text, Group, Input, Space, SimpleGrid, ThemeIcon } from '@mantine/core';
import { IconClock, IconList, IconBell } from '@tabler/icons-react';

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${inter.className}`}>
        <Container>
          <header height={60} mb={30} p="md">
            <Group position="apart">
              <Text weight={700} size="xl">ImmoRadar</Text>
            </Group>
          </header>
          <Text align="center" weight={700} size="xl">Alle Immobilienangebote an einem Ort</Text>
          <Space h="md" />
          <Group position="center">
            <Input
              placeholder="Suche..."
              size="md"
              style={{ width: '60%' }}
            />
            {/* todo filter */}
          </Group>
          <Space h="xl" />
          <SimpleGrid cols={3} spacing="lg" breakpoints={[{ maxWidth: 'sm', cols: 1 }]}>
            <Group position="center">
              <ThemeIcon radius="xl" size="lg">
                <IconClock size={24} />
              </ThemeIcon>
              <Text>Kein mühsames Durchsuchen mehrerer Webseiten</Text>
            </Group>
            <Group position="center">
              <ThemeIcon radius="xl" size="lg">
                <IconList size={24} />
              </ThemeIcon>
              <Text>Eine einzige, gut sortierte Liste ohne Duplikate</Text>
            </Group>
            <Group position="center">
              <ThemeIcon radius="xl" size="lg">
                <IconBell size={24} />
              </ThemeIcon>
              <Text>Sofortige Updates bei neuen Angeboten</Text>
            </Group>
          </SimpleGrid>
        </Container>
      </main>
    </>
  );
}
