import Head from "next/head";
import Link from "next/link";
import { AppShell, Burger, Title, Flex, NavLink } from '@mantine/core';
import { useDisclosure } from '@mantine/hooks';

function Layout({ children }) {
  const [opened, { toggle }] = useDisclosure();

  return (
    <>
      <Head>
        <title>ImmoRadar Admin</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <AppShell
        header={{ height: 60 }}
        navbar={{
          width: 300,
          breakpoint: 'sm',
          collapsed: { mobile: !opened },
        }}
        padding="md"
      >
        <AppShell.Header>
          <Burger
            opened={opened}
            onClick={toggle}
            hiddenFrom="sm"
            size="sm"
          />
          <Flex align="center" ml="md" h="100%">
            <Title order={2}>ImmoRadar Admin</Title>
          </Flex>
        </AppShell.Header>

        <AppShell.Navbar p="md">
          <NavLink
            component={Link}
            href="/"
            label="Logs"
          />
          <NavLink
            component={Link}
            href="/fields"
            label="Felder"
          />
          <NavLink
            component={Link}
            href="/emails"
            label="Emails"
          />
        </AppShell.Navbar>

        <AppShell.Main>
          { children }
        </AppShell.Main>
      </AppShell>
    </>
  );
}

export default Layout