export const featureMap = {
  'FULLY_FURNISHED': 'Möbliert/Teilmöbliert',
  'BALCONY': 'Balkon',
  'FITTED_KITCHEN': 'Einbauküche',
  'BATH_WITH_TUB': 'Badewanne',
  'WHEELCHAIR_ACCESSIBLE': 'Stufenloser Zugang',
  'UNDERFLOOR_HEATING': 'Fußbodenheizung',
  'NEW_BUILDING': 'Neubau',
  'PASSENGER_LIFT': 'Aufzug',
  'CAR_PARK': 'Garage/Stellplatz',
  'GARDEN_SHARED': 'Garten/-mitnutzung',
  'PETS_ALLOWED': 'Haustiere erlaubt',
  'GUEST_TOILET': 'Gäste WC',
  'BASEMENT': 'Keller',
  'FLAT_SHARE_POSSIBLE': 'WG-geeignet',
  'OLD_BUILDING': 'Altbau',
  'TERRACE': 'Terrasse',
  'CERTIFICATE_OF_ELIGIBILITY': 'WBS benötigt',
  'ATTIC': 'Dachboden',
  'GROUND_FLOOR': 'Erdgeschoss',
  'CELLAR_SHARE': 'Kelleranteil',
  'BARRIER_FREE': 'Barrierefrei',
  'BATH_WITH_WINDOW': 'Bad mit Fenster',
  'GARDEN': 'Garten',
  'FULLY_RENOVATED': 'Komplett renoviert',
  'PARTLY_FURNISHED': 'Teilweise möbliert',
  'AVAILABLE_FOR_RENT': 'Verfügbar zur Miete',
  'UNDERGROUND_PARKING': 'Tiefgarage',
  'PARKING_AREA': 'Parkplatz',
  'GARAGE': 'Garage',
  'LOGGIA': 'Loggia',
  'FREIGHT_ELEVATOR': 'Lastenaufzug',
  'FIRST_TIME_USE': 'Erstbezug',
  'GARDEN_PART': 'Gartenanteil',
  'SENIOR_FRIENDLY': 'Seniorenfreundlich',
  'DOUBLE_PARKER': 'Doppelparker',
  'PARTLY_AIR_CONDITIONED': 'Teilweise klimatisiert',
  'RENTED': 'Vermietet',
  'AIR_CONDITIONED': 'Klimatisiert',
  'RENOVATED': 'Renoviert'
};