export const featureMap = {
  'FLAT_SHARE_POSSIBLE': 'WG-geeignet',
  'CERTIFICATE_OF_ELIGIBILITY': 'WBS benötigt',
  'GARDEN': 'Garten',
  'FULLY_FURNISHED': 'Möbliert',
  'BALCONY': 'Balkon',
  'FITTED_KITCHEN': 'Einbauküche',
  'NEW_BUILDING': 'Neubau',
  'OLD_BUILDING': 'Altbau',
  'BATH_WITH_TUB': 'Badewanne',
  'WHEELCHAIR_ACCESSIBLE': 'Stufenloser Zugang',
  'UNDERFLOOR_HEATING': 'Fußbodenheizung',
  'PASSENGER_LIFT': 'Aufzug',
  'CAR_PARK': 'Garage/Stellplatz',
  'GARDEN_SHARED': 'Garten/-mitnutzung',
  'PETS_ALLOWED': 'Haustiere erlaubt',
  'GUEST_TOILET': 'Gäste WC',
  'BASEMENT': 'Keller',
  'TERRACE': 'Terrasse',
  'ATTIC': 'Dachboden',
  'GROUND_FLOOR': 'Erdgeschoss',
  'BATH_WITH_WINDOW': 'Bad mit Fenster',
  'FULLY_RENOVATED': 'Renoviert',
  'PARTLY_FURNISHED': 'Teilweise möbliert',
  'LOGGIA': 'Loggia',
  'FREIGHT_ELEVATOR': 'Lastenaufzug',
  'FIRST_TIME_USE': 'Erstbezug',
  'SENIOR_FRIENDLY': 'Seniorenfreundlich',
  'AIR_CONDITIONED': 'Klimatisiert',
};